services:
  web:
    build:
      context: .
    command: ["/bin/sh", "-c", "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"]
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/mediafiles
    expose:
     - 8000
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/app/staticfiles
      - media_files:/app/mediafiles
volumes:
  static_files:
  media_files: