name: Django CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  lint-and-test:
    runs-on: ubuntu-latest  

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest stable version

    # Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v4  # Updated to version 4
      with:
        python-version: '3.10'  # Ensure Python 3.10 is used

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black  # Install Flake8 and Black

    # Run Black for code formatting
    - name: Run Black (code formatting)
      run: |
        black --check .  # Check if Black is properly formatting the code

    # Run Flake8 for linting
    - name: Run Flake8 (linting)
      run: |
        flake8 .  # Lint the codebase

    # Set up SQLite3 database and run Django tests
    - name: Set up SQLite3 database and run Django tests
      run: |
        python manage.py migrate  # Migrate the SQLite3 database
        python manage.py test  # Run the tests

    # Display the test results
    - name: Collect test results
      if: success()
      run: |
        echo "All tests passed"
